---
name: Full Lint of Main

# Run linter on push
on:
  workflow_dispatch:
    
jobs:
  build:
    name: Full Lint of Main
    runs-on: ubuntu-latest
     
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        # Use the slim linter to speed up build and download time
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: false
          VALIDATE_BASH_EXEC: false
          VALIDATE_GROOVY: false
          VALIDATE_JSON: false
          DEFAULT_BRANCH: main
          JAVA_FILE_NAME: sun_check.xml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}